# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Syracuse University Hockey Analytics Club"                                # Your name
  description: "A club for people who love hockey and numbers"   # A brief slogan (optional)
  site-url: "https://su_hockeyclub.netlify.app/"
  image: img/my_image.jpg
  
  favicon: img/wordlogo_bluewhite.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/wordlogo_bluewhite.png
    
    # your sub-pages
    
    # your social media handles
    right:
      - text: "Schedule"
        href: schedule/index.qmd
      - text: "Activities"
        href: activities/index.qmd        
      - text: "Blog"
        href: blog/index.qmd
      - text: "Photos"
        href: photography/index.qmd      
      - icon: twitter
        href: https://twitter.com/su_hockeyclub
      - icon: instagram
        href: https://www.instagram.com/su_hockeyclub/       
      - icon: envelope
        aria-label: email
        href: "mailto:dbgold@syr.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    right: |
      <span class="faux-block"><a href="https://github.com/qrobnett23/suhac_website">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true